version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: app-global-task
        LoadBalancerInfo:
          ContainerName: app
          ContainerPort: 8000