version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Entrando no frontend..."
      - cd frontend
      - npm install

  build:
    commands:
      - echo "Buildando frontend..."
      - npm run build

  post_build:
    commands:
      - echo "Subindo para S3..."
      - aws s3 sync dist/ s3://aramis-app-global-regiao01-prd --delete
      - aws s3 sync dist/ s3://aramis-app-global-regiao02-prod --delete

artifacts:
  files:
    - '**/*'