# CloudFormation Template
AWSTemplateFormatVersion: "2010-09-09"
Description: "Root stack - creates Network layer using nested stack (templates/network.yaml)"

Parameters:
  ProjectName:
    Type: String
    Default: "myproject"
    Description: "Prefix used in resource names/tags"

  Environment:
    Type: String
    Default: "dev"
    AllowedValues: ["dev", "hml", "prod", "dr"]
    Description: "Environment name"

  # Bucket/prefix onde os templates (inclusive templates/network.yaml) foram publicados
  TemplateBucket:
    Type: String
    Description: "S3 bucket that stores CloudFormation templates"

  TemplatePrefix:
    Type: String
    Default: "artifacts/cloudformation"
    Description: "S3 prefix/folder where templates are stored"

  # Parâmetros repassados ao módulo de rede
  VpcCidr:
    Type: String
    Default: "10.0.0.0/16"

  PublicSubnet1Cidr:
    Type: String
    Default: "10.0.1.0/24"

  PublicSubnet2Cidr:
    Type: String
    Default: "10.0.2.0/24"

  EnableDnsHostnames:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]

  EnableDnsSupport:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      # O arquivo precisa estar no S3 nesse caminho:
      # s3://<TemplateBucket>/<TemplatePrefix>/templates/network.yaml
      TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}/templates/network.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        VpcCidr: !Ref VpcCidr
        PublicSubnet1Cidr: !Ref PublicSubnet1Cidr
        PublicSubnet2Cidr: !Ref PublicSubnet2Cidr
        EnableDnsHostnames: !Ref EnableDnsHostnames
        EnableDnsSupport: !Ref EnableDnsSupport

Outputs:
  VpcId:
    Description: "VPC ID (from nested NetworkStack)"
    Value: !GetAtt NetworkStack.Outputs.VpcId
    Export:
      Name: !Sub "${ProjectName}-${Environment}-VpcId"

  PublicSubnetIds:
    Description: "Public subnet IDs (from nested NetworkStack)"
    Value: !GetAtt NetworkStack.Outputs.PublicSubnetIds
    Export:
      Name: !Sub "${ProjectName}-${Environment}-PublicSubnetIds"

  PublicRouteTableId:
    Description: "Public route table ID (from nested NetworkStack)"
    Value: !GetAtt NetworkStack.Outputs.PublicRouteTableId
    Export:
      Name: !Sub "${ProjectName}-${Environment}-PublicRouteTableId"

  InternetGatewayId:
    Description: "IGW ID (from nested NetworkStack)"
    Value: !GetAtt NetworkStack.Outputs.InternetGatewayId
    Export:
      Name: !Sub "${ProjectName}-${Environment}-InternetGatewayId"
