version: 0.2

env:
  variables:
    STACK_NAME: "app-global-infra"
    TEMPLATE_FILE: "infra/root.yaml"
    PACKAGED_FILE: "infra/packaged.yaml"

    # Bucket onde o CloudFormation "package" vai subir os templates 
    # Use um bucket na MESMA região do deploy
    TEMPLATE_BUCKET: "aramis-projeto-app-global"
    TEMPLATE_PREFIX: "app-global/infra"

    # Nome da role de execução do CloudFormation 
    CFN_EXEC_ROLE_NAME: "Role_app_global_infra"

phases:
  install:
    commands:
      - aws --version

  pre_build:
    commands:
      - echo "Validando template..."
      - echo "TEMPLATE_FILE=[$TEMPLATE_FILE]"
      - echo "TEMPLATE_BUCKET=[$TEMPLATE_BUCKET]"
      - ls -la infra || true
      - test -f "$TEMPLATE_FILE"
      - aws cloudformation validate-template --template-body file://$TEMPLATE_FILE

  build:
    commands:
      - echo "Obtendo Account ID..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

      - echo "Montando ARN da Execution Role do CloudFormation..."
      - CFN_EXEC_ROLE_ARN="arn:aws:iam::${ACCOUNT_ID}:role/${CFN_EXEC_ROLE_NAME}"
      - echo "CFN_EXEC_ROLE_ARN=${CFN_EXEC_ROLE_ARN}"

      - echo "Packaging (upload para S3)..."
      - aws cloudformation package --template-file "infra/root.yaml" --s3-bucket "aramis-projeto-app-global" --s3-prefix "app-global/infra" --output-template-file "infra/packaged.yaml"

      - echo "Deploy (Create/Update Stack) usando Execution Role..."
      - aws cloudformation deploy --debug --stack-name "app-global-infra" --template-file "infra/packaged.yaml" --capabilities CAPABILITY_NAMED_IAM --role-arn "arn:aws:iam::181317788381:role/Role_app_global_infra" --no-fail-on-empty-changeset --parameter-overrides TemplateBucket="aramis-projeto-app-global" TemplatePrefix="app-global/infra"

artifacts:
  files:
    - infra/packaged.yaml

