version: 0.2

phases:
  install:
    commands:
      - aws --version

  pre_build:
    commands:
      - echo "Validando template..."
      - echo "TEMPLATE_FILE=[infra/root.yaml]"
      - echo "TEMPLATE_BUCKET=[aramis-projeto-app-global]"
      - ls -la infra || true
      - test -f "infra/root.yaml"
      - aws cloudformation validate-template --template-body file://infra/root.yaml

  build:
    commands:
      - echo "Montando ARN da Execution Role do CloudFormation..."
      - CFN_EXEC_ROLE_ARN="arn:aws:iam::181317788381:role/Role_app_global_infra"
      - echo "CFN_EXEC_ROLE_ARN=${CFN_EXEC_ROLE_ARN}"

      - echo "Packaging (upload para S3)..."
      - aws cloudformation package \
          --template-file "infra/root.yaml" \
          --s3-bucket "aramis-projeto-app-global" \
          --s3-prefix "app-global/infra" \
          --output-template-file "infra/packaged.yaml"

      - echo "Deploy (Create/Update Stack) usando Execution Role..."
      - aws cloudformation deploy \
          --stack-name "app-global-infra" \
          --template-file "infra/packaged.yaml" \
          --capabilities CAPABILITY_NAMED_IAM \
          --role-arn "$CFN_EXEC_ROLE_ARN" \
          --no-fail-on-empty-changeset

artifacts:
  files:
    - infra/packaged.yaml
