AWSTemplateFormatVersion: "2010-09-09"
Description: "Root stack - creates Network layer using nested stack (templates/network.yaml)"

Parameters:
  ProjectName:
    Type: String
    Default: "app-global"
    Description: "Prefix used in resource names/tags"

  Environment:
    Type: String
    Default: "prd"
    AllowedValues: ["dev", "hml", "prd", "dr"]
    Description: "Environment name"

  # Bucket/prefix onde os templates (inclusive templates/network.yaml) foram publicados
  TemplateBucket:
    Type: String
    Description: "S3 bucket that stores CloudFormation templates"

  TemplatePrefix:
    Type: String
    Default: "artifacts/cloudformation"
    Description: "S3 prefix/folder where templates are stored"

  # Parâmetros repassados ao módulo de rede
  VpcCidr:
    Type: String
    Default: "10.0.0.0/16"

  # PublicSubnet1Cidr:
  #   Type: String
  #   Default: "10.0.1.0/24"

  # PublicSubnet2Cidr:
  #   Type: String
  #   Default: "10.0.2.0/24"

  PrivateSubnet1Cidr:
    Type: String
    Default: "10.0.1.0/24"

  PrivateSubnet2Cidr:
    Type: String
    Default: "10.0.2.0/24"

  EnableDnsHostnames:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]

  EnableDnsSupport:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
  
  DomainName:
    Type: String
    Default: www.aramislabs.click

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      # O arquivo precisa estar no S3 nesse camin
      # s3://<TemplateBucket>/<TemplatePrefix>/templates/network.yaml
      #TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/${TemplatePrefix}/templates/network.yaml"
      TemplateURL: templates/network.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        VpcCidr: !Ref VpcCidr
        #PublicSubnet1Cidr: !Ref PublicSubnet1Cidr
        #PublicSubnet2Cidr: !Ref PublicSubnet2Cidr
        PrivateSubnet1Cidr: !Ref PrivateSubnet1Cidr
        PrivateSubnet2Cidr: !Ref  PrivateSubnet2Cidr
        EnableDnsHostnames: !Ref EnableDnsHostnames
        EnableDnsSupport: !Ref EnableDnsSupport
        #ServiceSecurityGroupId: !GetAtt EcsStack.Outputs.ServiceSecurityGroupId
  
  EndpointsStack:
   Type: AWS::CloudFormation::Stack
   DeletionPolicy: Delete
   UpdateReplacePolicy: Delete
   Properties:
    TemplateURL: templates/Endpoint.yaml
    Parameters:
      ProjectName: !Ref ProjectName
      Environment: !Ref Environment
      VPC: !GetAtt NetworkStack.Outputs.VpcId
      PrivateSubnet1: !GetAtt NetworkStack.Outputs.PrivateSubnet1Id
      PrivateSubnet2: !GetAtt NetworkStack.Outputs.PrivateSubnet2Id
      PrivateRouteTable: !GetAtt NetworkStack.Outputs.PrivateRouteTableId
      #ServiceSecurityGroupId: !GetAtt EcsStack.Outputs.ServiceSecurityGroupId      

  AlbStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/alb.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        #PublicSubnetIds: !Split [",", !GetAtt NetworkStack.Outputs.PublicSubnetIds]
        #PublicSubnetIds: !GetAtt NetworkStack.Outputs.PublicSubnetIds    
        PublicSubnetIds: !GetAtt NetworkStack.Outputs.PrivateSubnetIds

  DynamoDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/DynamoDB.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
# ECS
  EcsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - EndpointsStack
    Properties:
      TemplateURL: templates/ECS.yaml
      Parameters:
        ProjectName: "app-global"
        DeploymentControllerType: "CODE_DEPLOY"
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        #PrivateSubnetIds: !Split [",", !GetAtt NetworkStack.Outputs.PublicSubnetIds]
        #PrivateSubnetIds: !GetAtt NetworkStack.Outputs.PrivateSubnetIds 
        PrivateSubnetIds: !GetAtt NetworkStack.Outputs.PrivateSubnetIds
        #PrivateSubnetIds: !GetAtt NetworkStack.Outputs.PrivateSubnetIds
        AlbSecurityGroupId: !GetAtt AlbStack.Outputs.AlbSecurityGroupId
        AlbListenerArn: !GetAtt AlbStack.Outputs.AlbHttpListenerArn
        ListenerRulePriority: 10
        PathPattern: "/*"
        ContainerPort: 8000
        DesiredCount: 2
        AssignPublicIp: "DISABLED"
        ImageUri: "181317788381.dkr.ecr.us-east-1.amazonaws.com/app_global:build-64"
        #ImageUri: vpce-0fd26765dc55e7d37-3swwss2w.dkr.ecr-fips.us-east-1.vpce.amazonaws.com
        HealthCheckPath: "/health"
        EnvironmentEmployeesTable: "Employees"
        EnvironmentClockTable: "ClockRecords"


  VpcLinkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/vpc-link.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        #PublicSubnetIds: !GetAtt NetworkStack.Outputs.PublicSubnetIds
        PrivateSubnetIds: !GetAtt NetworkStack.Outputs.PrivateSubnetIds
 # Api gateway 
  ApiGatewayStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VpcLinkStack
      - AlbStack
    Properties:
      TemplateURL: templates/apigw.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        VpcLinkId: !GetAtt VpcLinkStack.Outputs.VpcLinkId
        #AlbInternalDnsName: !GetAtt AlbStack.Outputs.AlbDnsName
        AlbHttpListenerArn: !GetAtt AlbStack.Outputs.AlbHttpListenerArn
        ApiCustomDomainName: apiglobal.aramislabs.click
        CertificateArn: arn:aws:acm:us-east-1:181317788381:certificate/fae7c3ad-e22b-4cc1-a055-f32bd357e039
        #HostedZoneName: aramislabs.click.
        #HostedZoneId: Z00421932FD8154X80J2A

# Frontend hosted in S3 Website
  FrontendStack:
     Type: AWS::CloudFormation::Stack
     DependsOn:
       - ApiGatewayStack
     Properties:
       TemplateURL: templates/s3.yaml
       Parameters:
         ProjectName: !Ref ProjectName
         Environment: !Ref Environment
         BucketName: !Sub "aramis-app-global-regiao01-${Environment}"
         #PriceClass: !FindInMap [EnvironmentConfig, !Ref Environment, PriceClass]

  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: FrontendStack
    Properties:
       TemplateURL: templates/cloudfront_waf.yaml
       Parameters:
         BucketName: !GetAtt FrontendStack.Outputs.BucketName
         DomainName: !Ref DomainName

Outputs:
  VpcId:
    Description: "VPC ID (from nested NetworkStack)"
    Value: !GetAtt NetworkStack.Outputs.VpcId
    Export:
      Name: !Sub "${ProjectName}-${Environment}-VpcId"

  # PublicSubnetIds:
  #   Description: "Public subnet IDs (from nested NetworkStack)"
  #   Value: !GetAtt NetworkStack.Outputs.PublicSubnetIds
  #   Export:
  #     Name: !Sub "${ProjectName}-${Environment}-PublicSubnetIds"

 
  PrivateSubnetIds:
    Description: "Public subnet IDs (from nested NetworkStack)"
    Value: !GetAtt NetworkStack.Outputs.PrivateSubnetIds
    Export:
      Name: !Sub "${ProjectName}-${Environment}-PrivateSubnetIds"


  # PublicRouteTableId:
  #   Description: "Public route table ID (from nested NetworkStack)"
  #   Value: !GetAtt NetworkStack.Outputs.PublicRouteTableId
  #   Export:
  #     Name: !Sub "${ProjectName}-${Environment}-PublicRouteTableId"


  PublicRouteTableId:
    Description: "Public route table ID (from nested NetworkStack)"
    Value: !GetAtt NetworkStack.Outputs.PrivateRouteTableId
    Export:
      Name: !Sub "${ProjectName}-${Environment}-PrivateRouteTableId"

  # InternetGatewayId:
  #   Description: "IGW ID (from nested NetworkStack)"
  #   Value: !GetAtt NetworkStack.Outputs.InternetGatewayId
  #   Export:
  #     Name: !Sub "${ProjectName}-${Environment}-InternetGatewayId"
 
  FrontendURL:
    Value: !GetAtt FrontendStack.Outputs.WebsiteURL
