version: 0.2

env:
  variables:
    #AWS_DEFAULT_REGION: us-east-1
    
    # APP/ECR
    ECR_REPO_NAME: minha-app

    # CloudFormation nested templates (onde o root.yml espera encontrar)
    TEMPLATE_BUCKET: aramis-projeto-app-global
    TEMPLATE_PREFIX: artifacts/cloudformation

    # Parâmetros do root.yml
    PROJECT_NAME: myproject
    ENVIRONMENT: dev

    ROOT_TEMPLATE: root.yml

phases:
  pre_build:
    commands:
      - set -e
      - REGION=${AWS_REGION}
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPO_NAME}

      - echo "Garantindo repo no ECR"
      - aws ecr describe-repositories --repository-names ${ECR_REPO_NAME} >/dev/null 2>&1 || aws ecr create-repository --repository-name ${ECR_REPO_NAME} >/dev/null

      - echo "Login no ECR"
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

      - IMAGE_TAG=$(echo "${CODEBUILD_RESOLVED_SOURCE_VERSION}" | cut -c 1-7)
      - echo "ECR_URI=${ECR_URI}"
      - echo "IMAGE_TAG=${IMAGE_TAG}"

  build:
    commands:
      - echo "Build e push do container (./app)"
      - docker build -t ${ECR_URI}:${IMAGE_TAG} ./app
      - docker push ${ECR_URI}:${IMAGE_TAG}

      - echo "Publicando nested templates no S3 no caminho esperado pelo root.yml"
      - aws s3 sync ./templates s3://${TEMPLATE_BUCKET}/${TEMPLATE_PREFIX}/templates/ --delete

  post_build:
    commands:
      - echo "Gerando cfn-config.json (parametros do root.yml)"
      - |
        cat > cfn-config.json <<EOF
        {
          "Parameters": {
            "ProjectName": "${PROJECT_NAME}",
            "Environment": "${ENVIRONMENT}",
            "TemplateBucket": "${TEMPLATE_BUCKET}",
            "TemplatePrefix": "${TEMPLATE_PREFIX}",
            "EcrUri": "${ECR_URI}",
            "ImageTag": "${IMAGE_TAG}"
          }
        }
        EOF
      - echo "Arquivos:"
      - ls -la ${ROOT_TEMPLATE} cfn-config.json

artifacts:
  files:
    - root.yml
    - cfn-config.json
