AWSTemplateFormatVersion: "2010-09-09"
Description: "ALB Stack (Security Group + ALB + HTTP Listener + Target Group)"

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
# Vpc and Subnets created in network template
  VpcId:
    Type: AWS::EC2::VPC::Id

  PublicSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

  AlbIngressCidr:
    Type: String
    Default: "0.0.0.0/0"
    Description: "CIDR allowed to access ALB port 80."

  # Porta do container no ECS
  TargetPort:
    Type: Number
    Default: 8080

  # Path de health check do seu app 
  HealthCheckPath:
    Type: String
    Default: "/health"
# SG for ALB
Resources:
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "${ProjectName}-${Environment}-alb-sg"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref AlbIngressCidr
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-alb-sg"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
# ALB with iinternal-scheme
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-alb"
      Scheme: internal
      Type: application
      IpAddressType: ipv4
      Subnets: !Ref PublicSubnetIds
      SecurityGroups:
        - !Ref AlbSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-alb"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment


# Main listener on port 80
  AlbHttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
      - Type: fixed-response
        FixedResponseConfig:
          StatusCode: "404"
          ContentType: "text/plain"
          MessageBody: "No rule matched"
# Test listener on port 8080 
  AlbHttpListenerTeste:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 8080
      Protocol: HTTP
      DefaultActions:
      - Type: fixed-response
        FixedResponseConfig:
          StatusCode: "404"
          ContentType: "text/plain"
          MessageBody: "No rule matched"
Outputs:
  AlbSecurityGroupId:
    Description: "ALB Security Group ID"
    Value: !Ref AlbSecurityGroup

  AlbHttpListenerArn:
    Description: "ALB HTTP Listener ARN"
    Value: !Ref AlbHttpListener

  AlbArn:
    Description: "ALB ARN"
    Value: !Ref ApplicationLoadBalancer

  AlbDnsName:
    Description: "ALB DNS Name"
    Value: !GetAtt ApplicationLoadBalancer.DNSName


