AWSTemplateFormatVersion: '2010-09-09'
Description: HTTP API (v2) with VPC Link integration to internal ALB

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
  VpcLinkId:
    Type: String
  #AlbInternalDnsName:
    #Type: String
  AlbHttpListenerArn:
    Type: String    

Resources:
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-api"
      ProtocolType: HTTP

  # Integration via VPC Link to your internal ALB.
  # Using HTTP_PROXY and forwarding path via {proxy}
  AlbVpcLinkIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: HTTP_PROXY
      IntegrationMethod: ANY
      ConnectionType: VPC_LINK
      ConnectionId: !Ref VpcLinkId
      PayloadFormatVersion: "1.0"
      #IntegrationUri: !Sub "http://${AlbInternalDnsName}/{proxy}"
      IntegrationUri: !Ref AlbHttpListenerArn


  # Routes
  EmployeesGetRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "GET /employees"
      Target: !Sub "integrations/${AlbVpcLinkIntegration}"

  EmployeesPostRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "POST /employees"
      Target: !Sub "integrations/${AlbVpcLinkIntegration}"

  ClockGetRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "GET /clock"
      Target: !Sub "integrations/${AlbVpcLinkIntegration}"

  ClockPostRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "POST /clock"
      Target: !Sub "integrations/${AlbVpcLinkIntegration}"

  ClockEmployeeIdGetRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "GET /clock/{employee_id}"
      Target: !Sub "integrations/${AlbVpcLinkIntegration}"

  HealthGetRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "GET /health"
      Target: !Sub "integrations/${AlbVpcLinkIntegration}"

  # Default stage
  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      #StageName: !Ref Environment
      StageName: "$default"
      AutoDeploy: true

Outputs:
  HttpApiId:
    Description: HTTP API Id
    Value: !Ref HttpApi

  InvokeUrl:
    Description: Invoke URL
    #Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/"