AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Static Website

Parameters:
  ProjectName:
    Type: String

  Environment:
    Type: String

  BucketName:
    Type: String

Resources:

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-frontend"

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: !Sub "arn:aws:s3:::${BucketName}/*"

Outputs:

  BucketName:
    Description: S3 bucket name
    Value: !Ref FrontendBucket

  WebsiteURL:
    Description: S3 Website URL
    Value: !GetAtt FrontendBucket.WebsiteURL
